### ISSUE TITLE
test after installation fails

### ISSUE THREAD

**Issue by telatin** [beardymcjohnface/Koverage#35]
**Describe the bug**
trying `koverage test` did't work.

**To Reproduce**

I installed the package as follows:

```bash
# from the repository directory
mamba create -n koverage python=3.10
conda activate koverage
pip install -e. 
koverage test
```

**Expected behavior**
Zero exit status from the command

**Screenshots or log files**
```text
....
Creating conda environment koverage/workflow/envs/minimap.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/telatina/git/private/Koverage/koverage/workflow/envs/minimap.yaml:
Command:
conda env create --quiet --file "/Users/telatina/git/private/Koverage/koverage/workflow/conda/316a10e7fc75d89ff163ef7383e4acd0_.yaml" --prefix "/Users/telatina/git/private/Koverage/koverage/workflow/conda/316a10e7fc75d89ff163ef7383e4acd0_"
Output:
/Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
/Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
/Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
/Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): ...working... /Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
/Users/telatina/miniconda3/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

Building graph of deps:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-64::__osx==14.2.1=0:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-64::__archspec==1=x86_64:  20%|██        | 1/5 [00:00<00:00, 9446.63it/s]
Examining @/osx-64::__unix==0=0:  40%|████      | 2/5 [00:00<00:00, 9811.24it/s]         
Examining minimap2[version='>=2.20']:  60%|██████    | 3/5 [00:00<00:00, 11418.25it/s]
Examining samtools[version='>=1.13']:  80%|████████  | 4/5 [00:00<00:00, 1234.62it/s] 
                                                                                     

Determining conflicts:   0%|          | 0/5 [00:00<?, ?it/s]
Examining conflict for samtools minimap2:   0%|          | 0/5 [00:00<?, ?it/s]
                                                                               
failed
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

Building graph of deps:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-64::__osx==14.2.1=0:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-64::__archspec==1=x86_64:  20%|██        | 1/5 [00:00<00:00, 11008.67it/s]
Examining @/osx-64::__unix==0=0:  40%|████      | 2/5 [00:00<00:00, 11915.64it/s]         
Examining minimap2[version='>=2.20']:  60%|██████    | 3/5 [00:00<00:00, 13148.29it/s]
Examining samtools[version='>=1.13']:  80%|████████  | 4/5 [00:00<00:00, 1289.07it/s] 
                                                                                     

Determining conflicts:   0%|          | 0/5 [00:00<?, ?it/s]
Examining conflict for samtools minimap2:   0%|          | 0/5 [00:00<?, ?it/s]
                                                                               
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libzlib conflicts for:
samtools[version='>=1.13'] -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']
samtools[version='>=1.13'] -> zlib -> libzlib[version='1.2.11|1.2.11|1.2.11|1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13',build='h9173be1_1012|h6c3fc93_1014|hfe4f2af_1|hfd90126_3|hfd90126_4|hfe4f2af_2|h6c3fc93_0|h9173be1_1013']

Package zlib conflicts for:
samtools[version='>=1.13'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']
minimap2[version='>=2.20'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0']
Note that strict channel priority may have removed packages required for satisfiability.


[2024:01:27 11:44:49] ERROR: Snakemake failed
```

**System (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Program version: version 0.1.8

**Additional context**

I also tried to address the zstandard issue with
```bash
mamba install zstandard
pip install --upgrade --force-reinstall zstandard
pip install --upgrade --force-reinstall zstd
```
but still got a problem at the minimap environment creation
```text
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libzlib conflicts for:
samtools[version='>=1.13'] -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']
samtools[version='>=1.13'] -> zlib -> libzlib[version='1.2.11|1.2.11|1.2.11|1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13',build='h9173be1_1012|h9173be1_1013|h6c3fc93_1014|h6c3fc93_0|hfd90126_3|hfd90126_4|hfe4f2af_2|hfe4f2af_1']

Package zlib conflicts for:
samtools[version='>=1.13'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']
minimap2[version='>=2.20'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0']
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by beardymcjohnface** [comment]
Thank you very much Andrea. I believe this should be fixed now. I've updated the unit tests to use strict channel priority to hopefully prevent this happening again. Can you try pulling the new release? On Mac you can run `koverage test map kmer`, however coverm only supports linux and the coverm wrapper will not build for MacOS.

**Comment by lparsons** [comment]
@beardymcjohnface I just rant into the same issue when testing for the JOSS submission (https://github.com/openjournals/joss-reviews/issues/6235#issuecomment-1912677208). I can see that you have merged a fix in version 0.1.9, but I don't think that version has been pushed out to bioconda yet (bioconda still shows 0.1.9). Instead, I used `pip` to install the updated version (`pip install -U koverage`) in the existing conda environment. That did seem to fix the tests, thanks!

Can you let us know once the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/42a59f02753f51656bf279efeda39d97cee0f2a2/recipes/koverage/meta.yaml) gets updated, it would be nice to have everything in sync, and I suspect it'll  just take some time to get updated.

**Comment by beardymcjohnface** [comment]
Hi Lance, the 0.1.9 is now merged with bioconda-recipes so it should be available after the nightly build.

**Comment by beardymcjohnface** [comment]
Actually I just checked and it seems to be available now. Let me know how it goes!

**Comment by telatin** [comment]
> Thank you very much Andrea. I believe this should be fixed now. I've updated the unit tests to use strict channel priority to hopefully prevent this happening again. Can you try pulling the new release? On Mac you can run `koverage test map kmer`, however coverm only supports linux and the coverm wrapper will not build for MacOS.

Thanks a million! It wasn't working on linux either, will try in both systems (skipping coverm for macos :))

**Comment by telatin** [comment]
LGTM
